# sync-works.ps1
# Build works.json (used by the museum in rpg.html) from the #timeline-view
# section of index.html. Run after adding works to index.html, then commit
# works.json together with index.html. index.html stays the single source.
# Executable part is ASCII only to avoid PowerShell 5.1 code-page issues.

$ErrorActionPreference = 'Stop'
$repo = $PSScriptRoot
if (-not $repo) { $repo = Split-Path -Parent $MyInvocation.MyCommand.Path }
Set-Location $repo

$html = [IO.File]::ReadAllText((Join-Path $repo 'index.html'), [Text.Encoding]::UTF8)

# Slice the timeline view (genre view is generated by JS and stays empty in HTML)
$start = $html.IndexOf('id="timeline-view"')
$end   = $html.IndexOf('id="genre-view"')
if ($start -lt 0 -or $end -le $start) { throw 'timeline-view section not found in index.html' }
$tl = $html.Substring($start, $end - $start)

function Decode-Entities([string]$s) {
  $s = $s -replace '&ensp;', ' '
  $s = $s -replace '&nbsp;', ' '
  $s = $s -replace '&amp;', '&'
  return $s
}
function Strip-Tags([string]$s) { return ($s -replace '<[^>]+>', '') }

$sep = [string][char]0x30FB   # katakana middle dot, joins several category tags

$years = @()
$yearMatches = [regex]::Matches($tl, '(?s)<div class="year-block">\s*<h3>(\d{4})</h3>\s*<ul class="work-list">(.*?)</ul>')
foreach ($ym in $yearMatches) {
  $items = @()
  foreach ($li in [regex]::Matches($ym.Groups[2].Value, '(?s)<li>(.*?)</li>')) {
    $liHtml = $li.Groups[1].Value
    $m = ''
    $mm = [regex]::Match($liHtml, '<span class="month">(.*?)</span>')
    if ($mm.Success) { $m = (Strip-Tags $mm.Groups[1].Value).Trim() }
    $jm = [regex]::Match($liHtml, '(?s)<span class="t-ja">(.*?)</span><span class="t-en">')
    $ja = if ($jm.Success) { $jm.Groups[1].Value } else { $liHtml }
    # category = text of the leading <a class="tag ...">; several tags join with a middle dot
    $cats = @()
    foreach ($tm in [regex]::Matches($ja, '<a [^>]*class="tag[^"]*"[^>]*>(.*?)</a>')) {
      $cats += (Strip-Tags $tm.Groups[1].Value).Trim()
    }
    $c = ($cats -join $sep)
    # title = ja text minus the category anchors, remaining markup stripped
    $t = [regex]::Replace($ja, '(?s)<a [^>]*class="tag[^"]*"[^>]*>.*?</a>', '')
    $t = Decode-Entities (Strip-Tags $t)
    $t = ($t -replace '\s+', ' ').Trim()
    if ($m -or $c -or $t) { $items += [ordered]@{ m = $m; c = $c; t = $t } }
  }
  $years += [ordered]@{ y = $ym.Groups[1].Value; items = @($items) }
}
if ($years.Count -lt 10) { throw "parse looks wrong: only $($years.Count) year blocks" }

# Write only when content really changed (UTF-8 without BOM, LF)
$json = ConvertTo-Json @($years) -Depth 6
$json = ($json -replace "`r`n", "`n") + "`n"
$path = Join-Path $repo 'works.json'
$old = ''
if (Test-Path $path) { $old = [IO.File]::ReadAllText($path, [Text.Encoding]::UTF8) }
if ($json -ne $old) {
  [IO.File]::WriteAllText($path, $json, (New-Object Text.UTF8Encoding($false)))
  Write-Output ("works.json updated (" + $years.Count + " years)")
} else {
  Write-Output 'works.json unchanged'
}
